import type {
  AdminCategoryTreeNode,
  AdminFilterTreeNode,
  AdminFiltersCategoriesPayload,
  AdminRuleManualProduct,
} from "./admin-filters-categories-types";

const ADMIN_FILTERS_CATEGORIES_ENDPOINT = "/api/admin/filters-categories";
const FILTERS_ENDPOINT = `${ADMIN_FILTERS_CATEGORIES_ENDPOINT}/filters`;
const CATEGORIES_ENDPOINT = `${ADMIN_FILTERS_CATEGORIES_ENDPOINT}/categories`;

function delay(ms: number) {
  return new Promise((resolve) => window.setTimeout(resolve, ms));
}

const productLibrary: AdminRuleManualProduct[] = [
  {
    product_id: 41021,
    source_id: 8,
    source_name: "LN-CC",
    vendor: "The Row",
    title: "The Row Camil silk twill oversized shirt in ivory",
    url: "https://www.ln-cc.com/en-ru/women/clothing/shirts/the-row-camil-silk-twill-oversized-shirt",
    status: "active",
    image_url: "https://images.unsplash.com/photo-1529139574466-a303027c1d8b?auto=format&fit=crop&w=400&q=80",
    matched_local_categories: ["women", "shirts", "ready-to-wear"],
    price_label: "€1,290",
    inventory_hint: "Последний размер S",
    last_seen_at: "2026-06-11T18:24:00Z",
  },
  {
    product_id: 41022,
    source_id: 4,
    source_name: "Browns",
    vendor: "Bottega Veneta",
    title: "Bottega Veneta Small Andiamo intrecciato leather bag",
    url: "https://www.brownsfashion.com/uk/shopping/bottega-veneta-small-andiamo-intrecciato-leather-bag",
    status: "active",
    image_url: "https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=400&q=80",
    matched_local_categories: ["women", "bags", "top-handle-bags"],
    price_label: "£3,250",
    inventory_hint: "В наличии 3 цвета",
    last_seen_at: "2026-06-12T07:42:00Z",
  },
  {
    product_id: 41023,
    source_id: 11,
    source_name: "SSENSE",
    vendor: "Loro Piana",
    title: "Loro Piana Windmate cashmere bomber jacket in navy",
    url: "https://www.ssense.com/en-us/men/product/loro-piana/windmate-cashmere-bomber-jacket",
    status: "active",
    image_url: "https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?auto=format&fit=crop&w=400&q=80",
    matched_local_categories: ["men", "outerwear", "jackets"],
    price_label: "$4,995",
    inventory_hint: "Полная размерная сетка",
    last_seen_at: "2026-06-12T03:10:00Z",
  },
  {
    product_id: 41024,
    source_id: 7,
    source_name: "Mytheresa",
    vendor: "Saint Laurent",
    title: "Saint Laurent grain de poudre wool blazer",
    url: "https://www.mytheresa.com/eu/en/women/saint-laurent-grain-de-poudre-wool-blazer",
    status: "active",
    image_url: "https://images.unsplash.com/photo-1523381210434-271e8be1f52b?auto=format&fit=crop&w=400&q=80",
    matched_local_categories: ["women", "tailoring", "blazers"],
    price_label: "€2,390",
    inventory_hint: "Размеры 34-42",
    last_seen_at: "2026-06-11T22:18:00Z",
  },
  {
    product_id: 41025,
    source_id: 12,
    source_name: "Mr Porter",
    vendor: "Prada",
    title: "Prada brushed leather derby shoes",
    url: "https://www.mrporter.com/en-gb/mens/product/prada/shoes/derby-shoes/brushed-leather-derby-shoes",
    status: "active",
    image_url: "https://images.unsplash.com/photo-1549298916-b41d501d3772?auto=format&fit=crop&w=400&q=80",
    matched_local_categories: ["men", "shoes", "derby-shoes"],
    price_label: "£1,050",
    inventory_hint: "Размеры 41-44",
    last_seen_at: "2026-06-10T16:05:00Z",
  },
  {
    product_id: 41026,
    source_id: 7,
    source_name: "Mytheresa",
    vendor: "Toteme",
    title: "Toteme signature double-faced wool coat",
    url: "https://www.mytheresa.com/eu/en/women/toteme-signature-double-faced-wool-coat",
    status: "active",
    image_url: "https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?auto=format&fit=crop&w=400&q=80",
    matched_local_categories: ["women", "outerwear", "coats"],
    price_label: "€1,180",
    inventory_hint: "Повторный завоз в конце недели",
    last_seen_at: "2026-06-11T10:32:00Z",
  },
  {
    product_id: 41027,
    source_id: 10,
    source_name: "Farfetch",
    vendor: "Miu Miu",
    title: "Miu Miu pleated gabardine mini skirt",
    url: "https://www.farfetch.com/shopping/women/miu-miu-pleated-gabardine-mini-skirt",
    status: "active",
    image_url: "https://images.unsplash.com/photo-1583496661160-fb5886a0aaaa?auto=format&fit=crop&w=400&q=80",
    matched_local_categories: ["women", "skirts", "mini-skirts"],
    price_label: "€1,490",
    inventory_hint: "Остались размеры 38 и 40",
    last_seen_at: "2026-06-12T05:11:00Z",
  },
  {
    product_id: 41028,
    source_id: 11,
    source_name: "SSENSE",
    vendor: "Khaite",
    title: "Khaite Benny studded leather belt",
    url: "https://www.ssense.com/en-us/women/product/khaite/benny-studded-leather-belt",
    status: "active",
    image_url: "https://images.unsplash.com/photo-1620799140408-edc6dcb6d633?auto=format&fit=crop&w=400&q=80",
    matched_local_categories: ["women", "accessories", "belts"],
    price_label: "$680",
    inventory_hint: "В наличии размеры XS-L",
    last_seen_at: "2026-06-09T21:48:00Z",
  },
  {
    product_id: 41029,
    source_id: 9,
    source_name: "LuisaViaRoma",
    vendor: "Brunello Cucinelli",
    title: "Brunello Cucinelli suede penny loafers",
    url: "https://www.luisaviaroma.com/en-gb/p/brunello-cucinelli/men/shoes",
    status: "active",
    image_url: "https://images.unsplash.com/photo-1560343090-f0409e92791a?auto=format&fit=crop&w=400&q=80",
    matched_local_categories: ["men", "shoes", "loafers"],
    price_label: "€920",
    inventory_hint: "Размеры 40-45",
    last_seen_at: "2026-06-08T12:15:00Z",
  },
  {
    product_id: 41030,
    source_id: 10,
    source_name: "Farfetch",
    vendor: "Loewe",
    title: "Loewe Puzzle Fold tote bag in shiny calfskin",
    url: "https://www.farfetch.com/shopping/women/loewe-puzzle-fold-tote-bag",
    status: "active",
    image_url: "https://images.unsplash.com/photo-1584917865442-de89df76afd3?auto=format&fit=crop&w=400&q=80",
    matched_local_categories: ["women", "bags", "tote-bags"],
    price_label: "€1,750",
    inventory_hint: "Есть в наличии в черном и tan",
    last_seen_at: "2026-06-11T19:07:00Z",
  },
  {
    product_id: 41031,
    source_id: 13,
    source_name: "Dover Street Market",
    vendor: "Rick Owens",
    title: "Rick Owens DRKSHDW cargo pods shorts",
    url: "https://shop.doverstreetmarket.com/products/rick-owens-drkshdw-cargo-pods",
    status: "draft",
    image_url: "https://images.unsplash.com/photo-1503341455253-b2e723bb3dbb?auto=format&fit=crop&w=400&q=80",
    matched_local_categories: ["men", "shorts", "avant-garde"],
    price_label: "£515",
    inventory_hint: "Черновик, без финальной цены",
    last_seen_at: "2026-06-07T09:22:00Z",
  },
  {
    product_id: 41032,
    source_id: 8,
    source_name: "LN-CC",
    vendor: "Jil Sander",
    title: "Jil Sander fine knit virgin wool turtleneck",
    url: "https://www.ln-cc.com/en-ru/men/clothing/knitwear/jil-sander-fine-knit-virgin-wool-turtleneck",
    status: "active",
    image_url: "https://images.unsplash.com/photo-1434389677669-e08b4cac3105?auto=format&fit=crop&w=400&q=80",
    matched_local_categories: ["men", "knitwear", "turtlenecks"],
    price_label: "€890",
    inventory_hint: "Осталось 2 размера",
    last_seen_at: "2026-06-12T08:02:00Z",
  },
];

function pickProducts(...ids: number[]) {
  return ids
    .map((id) => productLibrary.find((item) => item.product_id === id))
    .filter((item): item is AdminRuleManualProduct => Boolean(item));
}

const filters: AdminFilterTreeNode[] = [
  {
    id: 101,
    entity: "filter",
    label: "Раздел",
    slug: "section",
    parent_id: null,
    is_enabled: true,
    product_count: 1486,
    placement: "catalog_toolbar",
    selection_mode: "multiple",
    rules: {
      local_category_keywords: ["women", "men", "ready-to-wear", "accessories"],
      title_keywords: [],
      manual_products: [],
    },
    sample_hits: [
      { product_id: 41021, vendor: "The Row", title: "Camil silk twill oversized shirt", reason: "local_category_keyword" },
      { product_id: 41023, vendor: "Loro Piana", title: "Windmate cashmere bomber jacket", reason: "local_category_keyword" },
    ],
    audit: {
      updated_at: "2026-06-11T17:45:00Z",
      updated_by: "merchandise.lead@antonshell.com",
      source_note: "Базовый раздел каталога для верхнего фильтр-бара витрины.",
    },
    children: [
      {
        id: 102,
        entity: "filter",
        label: "Одежда",
        slug: "clothing",
        parent_id: 101,
        is_enabled: true,
        product_count: 764,
        placement: "catalog_toolbar",
        selection_mode: "multiple",
        rules: {
          local_category_keywords: ["shirts", "jackets", "knitwear", "skirts", "pants", "outerwear"],
          title_keywords: ["shirt", "coat", "jacket", "turtleneck"],
          manual_products: pickProducts(41021, 41023, 41024, 41026, 41027, 41032),
        },
        sample_hits: [
          { product_id: 41024, vendor: "Saint Laurent", title: "grain de poudre wool blazer", reason: "title_keyword" },
          { product_id: 41032, vendor: "Jil Sander", title: "fine knit virgin wool turtleneck", reason: "manual_product" },
        ],
        audit: {
          updated_at: "2026-06-12T06:14:00Z",
          updated_by: "taxonomy.editor@antonshell.com",
          source_note: "Включает ready-to-wear и верхнюю одежду без обуви и аксессуаров.",
        },
        children: [],
      },
      {
        id: 103,
        entity: "filter",
        label: "Обувь",
        slug: "shoes",
        parent_id: 101,
        is_enabled: true,
        product_count: 312,
        placement: "catalog_toolbar",
        selection_mode: "multiple",
        rules: {
          local_category_keywords: ["shoes", "derby-shoes", "loafers", "boots", "sneakers"],
          title_keywords: ["loafer", "derby", "boot", "sneaker"],
          manual_products: pickProducts(41025, 41029),
        },
        sample_hits: [
          { product_id: 41025, vendor: "Prada", title: "brushed leather derby shoes", reason: "local_category_keyword" },
          { product_id: 41029, vendor: "Brunello Cucinelli", title: "suede penny loafers", reason: "manual_product" },
        ],
        audit: {
          updated_at: "2026-06-10T13:05:00Z",
          updated_by: "buyer.footwear@antonshell.com",
          source_note: "Выделен отдельно, так как участвует в быстрой навигации каталога.",
        },
        children: [],
      },
      {
        id: 104,
        entity: "filter",
        label: "Сумки",
        slug: "bags",
        parent_id: 101,
        is_enabled: true,
        product_count: 188,
        placement: "catalog_toolbar",
        selection_mode: "multiple",
        rules: {
          local_category_keywords: ["bags", "tote-bags", "top-handle-bags", "crossbody-bags"],
          title_keywords: ["bag", "tote", "puzzle", "andiamo"],
          manual_products: pickProducts(41022, 41030),
        },
        sample_hits: [
          { product_id: 41022, vendor: "Bottega Veneta", title: "Small Andiamo intrecciato leather bag", reason: "manual_product" },
          { product_id: 41030, vendor: "Loewe", title: "Puzzle Fold tote bag in shiny calfskin", reason: "title_keyword" },
        ],
        audit: {
          updated_at: "2026-06-09T16:28:00Z",
          updated_by: "accessories.team@antonshell.com",
          source_note: "Служит для основного сценария поиска по сумкам на витрине.",
        },
        children: [],
      },
      {
        id: 105,
        entity: "filter",
        label: "Аксессуары",
        slug: "accessories",
        parent_id: 101,
        is_enabled: true,
        product_count: 222,
        placement: "catalog_toolbar",
        selection_mode: "multiple",
        rules: {
          local_category_keywords: ["accessories", "belts", "scarves", "hats", "sunglasses"],
          title_keywords: ["belt", "scarf", "cap"],
          manual_products: pickProducts(41028),
        },
        sample_hits: [
          { product_id: 41028, vendor: "Khaite", title: "Benny studded leather belt", reason: "manual_product" },
        ],
        audit: {
          updated_at: "2026-06-08T14:52:00Z",
          updated_by: "merchandise.lead@antonshell.com",
          source_note: "Исключает украшения, чтобы не размывать выдачу в каталоге.",
        },
        children: [],
      },
    ],
  },
  {
    id: 106,
    entity: "filter",
    label: "Пол",
    slug: "gender",
    parent_id: null,
    is_enabled: true,
    product_count: 1324,
    placement: "catalog_toolbar",
    selection_mode: "single",
    rules: {
      local_category_keywords: ["women", "men"],
      title_keywords: [],
      manual_products: [],
    },
    sample_hits: [
      { product_id: 41021, vendor: "The Row", title: "Camil silk twill oversized shirt", reason: "local_category_keyword" },
      { product_id: 41023, vendor: "Loro Piana", title: "Windmate cashmere bomber jacket", reason: "local_category_keyword" },
    ],
    audit: {
      updated_at: "2026-06-12T07:20:00Z",
      updated_by: "taxonomy.editor@antonshell.com",
      source_note: "Глобальный фильтр для быстрой разбивки мужского и женского каталога.",
    },
    children: [],
  },
  {
    id: 107,
    entity: "filter",
    label: "Наличие",
    slug: "availability",
    parent_id: null,
    is_enabled: true,
    product_count: 1168,
    placement: "catalog_toolbar",
    selection_mode: "single",
    rules: {
      local_category_keywords: ["in-stock", "pre-order"],
      title_keywords: ["available now", "pre-order"],
      manual_products: pickProducts(41031),
    },
    sample_hits: [
      { product_id: 41031, vendor: "Rick Owens", title: "DRKSHDW cargo pods shorts", reason: "manual_product" },
    ],
    audit: {
      updated_at: "2026-06-12T08:01:00Z",
      updated_by: "ops.catalog@antonshell.com",
      source_note: "Пока живет на моках, затем будет завязан на реальный статус карточки товара.",
    },
    children: [],
  },
  {
    id: 108,
    entity: "filter",
    label: "Новинки",
    slug: "new-arrivals",
    parent_id: null,
    is_enabled: true,
    product_count: 206,
    placement: "showcase_navigation",
    selection_mode: "single",
    rules: {
      local_category_keywords: ["new-arrivals", "latest-drop"],
      title_keywords: ["new season", "latest arrival"],
      manual_products: pickProducts(41022, 41027),
    },
    sample_hits: [
      { product_id: 41022, vendor: "Bottega Veneta", title: "Small Andiamo intrecciato leather bag", reason: "manual_product" },
      { product_id: 41027, vendor: "Miu Miu", title: "pleated gabardine mini skirt", reason: "manual_product" },
    ],
    audit: {
      updated_at: "2026-06-12T08:30:00Z",
      updated_by: "homepage.curator@antonshell.com",
      source_note: "Используется в верхней навигации витрины и на промо-подборках.",
    },
    children: [],
  },
  {
    id: 109,
    entity: "filter",
    label: "Дизайнеры",
    slug: "designers",
    parent_id: null,
    is_enabled: true,
    product_count: 514,
    placement: "search_refinement",
    selection_mode: "multiple",
    rules: {
      local_category_keywords: ["designers"],
      title_keywords: ["the row", "bottega", "saint laurent", "loewe", "miu miu"],
      manual_products: pickProducts(41021, 41022, 41024, 41030),
    },
    sample_hits: [
      { product_id: 41021, vendor: "The Row", title: "Camil silk twill oversized shirt", reason: "title_keyword" },
      { product_id: 41030, vendor: "Loewe", title: "Puzzle Fold tote bag in shiny calfskin", reason: "manual_product" },
    ],
    audit: {
      updated_at: "2026-06-11T20:18:00Z",
      updated_by: "brand.mapping@antonshell.com",
      source_note: "Фильтр для отдельной ветки дизайнеров и каталога брендов.",
    },
    children: [],
  },
];

const categories: AdminCategoryTreeNode[] = [
  {
    id: 201,
    entity: "category",
    label: "Женское",
    slug: "women",
    parent_id: null,
    is_enabled: true,
    product_count: 918,
    visibility: "public",
    route_path: "/catalog/women",
    rules: {
      local_category_keywords: ["women", "womenswear", "ladies"],
      title_keywords: [],
      manual_products: [],
    },
    sample_hits: [
      { product_id: 41021, vendor: "The Row", title: "Camil silk twill oversized shirt", reason: "local_category_keyword" },
      { product_id: 41024, vendor: "Saint Laurent", title: "grain de poudre wool blazer", reason: "local_category_keyword" },
    ],
    audit: {
      updated_at: "2026-06-12T05:40:00Z",
      updated_by: "taxonomy.editor@antonshell.com",
      source_note: "Корневая публичная ветка для женского каталога.",
    },
    children: [
      {
        id: 202,
        entity: "category",
        label: "Одежда",
        slug: "women-clothing",
        parent_id: 201,
        is_enabled: true,
        product_count: 534,
        visibility: "public",
        route_path: "/catalog/women/clothing",
        rules: {
          local_category_keywords: ["shirts", "skirts", "coats", "blazers", "dresses"],
          title_keywords: ["shirt", "coat", "blazer", "skirt"],
          manual_products: pickProducts(41021, 41024, 41026, 41027),
        },
        sample_hits: [
          { product_id: 41026, vendor: "Toteme", title: "signature double-faced wool coat", reason: "title_keyword" },
        ],
        audit: {
          updated_at: "2026-06-11T15:12:00Z",
          updated_by: "merchandise.lead@antonshell.com",
          source_note: "Ветка публичной навигации для женской одежды.",
        },
        children: [
          {
            id: 203,
            entity: "category",
            label: "Рубашки",
            slug: "women-shirts",
            parent_id: 202,
            is_enabled: true,
            product_count: 84,
            visibility: "public",
            route_path: "/catalog/women/clothing/shirts",
            rules: {
              local_category_keywords: ["shirts", "blouses"],
              title_keywords: ["shirt", "blouse"],
              manual_products: pickProducts(41021),
            },
            sample_hits: [
              { product_id: 41021, vendor: "The Row", title: "Camil silk twill oversized shirt", reason: "manual_product" },
            ],
            audit: {
              updated_at: "2026-06-12T06:48:00Z",
              updated_by: "taxonomy.editor@antonshell.com",
              source_note: "Используется для прямых переходов из навигации по одежде.",
            },
            children: [],
          },
          {
            id: 204,
            entity: "category",
            label: "Пиджаки",
            slug: "women-blazers",
            parent_id: 202,
            is_enabled: true,
            product_count: 61,
            visibility: "public",
            route_path: "/catalog/women/clothing/blazers",
            rules: {
              local_category_keywords: ["blazers", "tailoring"],
              title_keywords: ["blazer", "tailored"],
              manual_products: pickProducts(41024),
            },
            sample_hits: [
              { product_id: 41024, vendor: "Saint Laurent", title: "grain de poudre wool blazer", reason: "manual_product" },
            ],
            audit: {
              updated_at: "2026-06-09T12:40:00Z",
              updated_by: "buyer.readytowear@antonshell.com",
              source_note: "Чистая ветка tailoring без костюмных брюк.",
            },
            children: [],
          },
        ],
      },
      {
        id: 205,
        entity: "category",
        label: "Сумки",
        slug: "women-bags",
        parent_id: 201,
        is_enabled: true,
        product_count: 188,
        visibility: "public",
        route_path: "/catalog/women/bags",
        rules: {
          local_category_keywords: ["bags", "tote-bags", "top-handle-bags"],
          title_keywords: ["bag", "tote", "andiamo", "puzzle"],
          manual_products: pickProducts(41022, 41030),
        },
        sample_hits: [
          { product_id: 41022, vendor: "Bottega Veneta", title: "Small Andiamo intrecciato leather bag", reason: "manual_product" },
          { product_id: 41030, vendor: "Loewe", title: "Puzzle Fold tote bag in shiny calfskin", reason: "title_keyword" },
        ],
        audit: {
          updated_at: "2026-06-10T11:25:00Z",
          updated_by: "accessories.team@antonshell.com",
          source_note: "Используется как самостоятельный раздел в публичной навигации.",
        },
        children: [],
      },
    ],
  },
  {
    id: 206,
    entity: "category",
    label: "Мужское",
    slug: "men",
    parent_id: null,
    is_enabled: true,
    product_count: 568,
    visibility: "public",
    route_path: "/catalog/men",
    rules: {
      local_category_keywords: ["men", "menswear", "gentlemen"],
      title_keywords: [],
      manual_products: [],
    },
    sample_hits: [
      { product_id: 41023, vendor: "Loro Piana", title: "Windmate cashmere bomber jacket", reason: "local_category_keyword" },
      { product_id: 41025, vendor: "Prada", title: "brushed leather derby shoes", reason: "local_category_keyword" },
    ],
    audit: {
      updated_at: "2026-06-11T09:58:00Z",
      updated_by: "taxonomy.editor@antonshell.com",
      source_note: "Корневая публичная ветка мужского каталога.",
    },
    children: [
      {
        id: 207,
        entity: "category",
        label: "Верхняя одежда",
        slug: "men-outerwear",
        parent_id: 206,
        is_enabled: true,
        product_count: 104,
        visibility: "public",
        route_path: "/catalog/men/outerwear",
        rules: {
          local_category_keywords: ["outerwear", "jackets", "bombers"],
          title_keywords: ["bomber", "jacket"],
          manual_products: pickProducts(41023),
        },
        sample_hits: [
          { product_id: 41023, vendor: "Loro Piana", title: "Windmate cashmere bomber jacket", reason: "manual_product" },
        ],
        audit: {
          updated_at: "2026-06-12T04:05:00Z",
          updated_by: "buyer.outerwear@antonshell.com",
          source_note: "Содержит только мужскую outerwear-ветку без трикотажа.",
        },
        children: [],
      },
      {
        id: 208,
        entity: "category",
        label: "Обувь",
        slug: "men-shoes",
        parent_id: 206,
        is_enabled: true,
        product_count: 142,
        visibility: "public",
        route_path: "/catalog/men/shoes",
        rules: {
          local_category_keywords: ["shoes", "derby-shoes", "loafers"],
          title_keywords: ["derby", "loafer"],
          manual_products: pickProducts(41025, 41029),
        },
        sample_hits: [
          { product_id: 41029, vendor: "Brunello Cucinelli", title: "suede penny loafers", reason: "title_keyword" },
        ],
        audit: {
          updated_at: "2026-06-10T10:18:00Z",
          updated_by: "buyer.footwear@antonshell.com",
          source_note: "Мужская обувь, используется также в витринных подборках.",
        },
        children: [],
      },
      {
        id: 209,
        entity: "category",
        label: "Трикотаж",
        slug: "men-knitwear",
        parent_id: 206,
        is_enabled: true,
        product_count: 87,
        visibility: "public",
        route_path: "/catalog/men/knitwear",
        rules: {
          local_category_keywords: ["knitwear", "turtlenecks"],
          title_keywords: ["turtleneck", "knit"],
          manual_products: pickProducts(41032),
        },
        sample_hits: [
          { product_id: 41032, vendor: "Jil Sander", title: "fine knit virgin wool turtleneck", reason: "manual_product" },
        ],
        audit: {
          updated_at: "2026-06-11T18:51:00Z",
          updated_by: "buyer.readytowear@antonshell.com",
          source_note: "Публичная ветка для мужского knitwear.",
        },
        children: [],
      },
    ],
  },
  {
    id: 210,
    entity: "category",
    label: "Скидки",
    slug: "sale",
    parent_id: null,
    is_enabled: true,
    product_count: 173,
    visibility: "public",
    route_path: "/catalog/sale",
    rules: {
      local_category_keywords: ["sale", "markdown", "discounted"],
      title_keywords: ["sale"],
      manual_products: pickProducts(41031),
    },
    sample_hits: [
      { product_id: 41031, vendor: "Rick Owens", title: "DRKSHDW cargo pods shorts", reason: "manual_product" },
    ],
    audit: {
      updated_at: "2026-06-12T08:12:00Z",
      updated_by: "campaign.manager@antonshell.com",
      source_note: "Отдельная публичная ветка для дисконтной витрины.",
    },
    children: [],
  },
];

export async function fetchAdminFiltersCategoriesMock(): Promise<AdminFiltersCategoriesPayload> {
  await delay(420);
  return {
    endpoint: ADMIN_FILTERS_CATEGORIES_ENDPOINT,
    filters_endpoint: FILTERS_ENDPOINT,
    categories_endpoint: CATEGORIES_ENDPOINT,
    fetched_at: "2026-06-12T08:35:00Z",
    filters,
    categories,
    product_library: productLibrary,
  };
}
